export const TRIP_TYPES = [
  "waterfall",
  "religious",
  "attraction",
  "travel_agency",
  "town",
  "monument",
  "castle",
  "station",
  "village",
  "archaeological_site",
  "saddle",
  "bus_stop",
  "administrative",
  "cultural",
  "architecture",
  "hill_station",
  "lake",
  "beach",
  "natural",
  "wildlife",
  "historical",
  "entertainment",
  "tomb",
  "temple",
  "observatory",
  "market",
  "stepwell",
  "fort",
];

export const ACTIVITIES = [
  "food",
  "technology",
  "temple visit",
  "nightlife",
  "yoga",
  "skiing",
  "wildlife",
  "surfing",
  "shopping",
  "safari",
  "culture",
  "relaxing",
  "trekking",
  "hiking",
  "photography",
  "sightseeing",
  "history",
  "snow sports",
  "gondola ride",
  "shikara ride",
  "houseboat stay",
  "adventure sports",
  "meditation",
  "spirituality",
  "beach activities",
  "water sports",
  "tea tourism",
  "bird watching",
  "boating",
  "fishing",
  "camping",
  "nature",
  "river rafting",
  "desert safari",
  "studio tour",
  "shows",
  "theme parks",
];
